### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by aszepieniec** [TritonVM/triton-tui#6]
`triton-tui --help` says

```
Terminal User Interface to help debugging programs written for Triton VM.

Usage: triton-tui [OPTIONS] <PROGRAM>

Arguments:
  <PROGRAM>  File containing the program to run

Options:
  -i, --input <file>            File containing public input
  -n, --non-determinism <file>  JSON file containing all non-determinism
      --initial-state <file>    JSON file containing entire initial state
      --interrupt-cycle <u32>   The maximum number of cycles to run after any interaction, preventing a frozen TUI in infinite loops [default: 1000000]
  -h, --help                    Print help
  -V, --version                 Print version
```

This suggests that supplying the program is mandatory and that `triton-tui program.tasm --initial_state vm_state.json` is a valid command (provided the named files exist). However, running that command produces this error message:

```
error: the argument '<PROGRAM>' cannot be used with '--initial-state <file>'

Usage: triton-tui --initial-state <file> <PROGRAM>

For more information, try '--help'.
```

Alternatively to updating the documentation, maybe it's simpler to re-allow supplying the program and the vm state and add a check that the latter's program matches the former.

**Comment by jan-ferdinand** [comment]
I had hoped that clap would generate the necessary documentation automatically, but forgot to check again. The matter seems to be too complex to allow meaningful autogeneration. Thanks for raising the issue. :+1:
